Fixed building the project
TaleTime/TaleTime_2 pull request #57
Opened 2023-10-21 18:31 UTC by SamTV12345

This fixes the build of the TaleTime project.

2023-10-21 19:31 UTC, doba16 requested changes

2023-10-21 19:31 UTC, doba16 commented on .idea/workspace.xml
We should remove the .idea folder from the repository. It already has caused problems opening the project and I don't want to imagine pulling this to my machine destroying my IDE setup...

2023-10-21 19:55 UTC, BaerMitUmlaut commented on .idea/workspace.xml
There's a community maintained repositiory of gitignore files which has [some rules for IntelliJ IDEA](https://github.com/github/gitignore/blob/main/Global/JetBrains.gitignore), which you might want to use here. This would prevent this issue in the future without having to focus on not accidentally adding this folder.

2023-10-21 19:59 UTC, SamTV12345 commented on .idea/workspace.xml
Thanks for the link. We normally add .idea in the gitignore. But this seems even better.

2023-10-22 12:08 UTC, doba16 approved these changes

2023-10-22 12:18 UTC, merged